In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
from warnings import simplefilter
# ignore all future warnings
simplefilter(action='ignore', category=FutureWarning)

In [3]:
train_trans = pd.read_csv("C:/MSBAPM/Spring 2020/Data Science with Python/Project/ieee-fraud-detection/train_transaction.csv")
train_identity = pd.read_csv("C:/MSBAPM/Spring 2020/Data Science with Python/Project/ieee-fraud-detection/train_identity.csv")


In [4]:
# prints the percentage of null observations for every column in train_identity
for i in train_identity.columns:
    print(i, np.round(train_identity[i].isnull().sum()/train_identity.shape[0],2))

TransactionID 0.0
id_01 0.0
id_02 0.02
id_03 0.54
id_04 0.54
id_05 0.05
id_06 0.05
id_07 0.96
id_08 0.96
id_09 0.48
id_10 0.48
id_11 0.02
id_12 0.0
id_13 0.12
id_14 0.45
id_15 0.02
id_16 0.1
id_17 0.03
id_18 0.69
id_19 0.03
id_20 0.03
id_21 0.96
id_22 0.96
id_23 0.96
id_24 0.97
id_25 0.96
id_26 0.96
id_27 0.96
id_28 0.02
id_29 0.02
id_30 0.46
id_31 0.03
id_32 0.46
id_33 0.49
id_34 0.46
id_35 0.02
id_36 0.02
id_37 0.02
id_38 0.02
DeviceType 0.02
DeviceInfo 0.18


In [5]:
# prints the percentage of null observations for every column in train_trans
for i in train_trans.columns:
    print(i, np.round(train_trans[i].isnull().sum()/train_trans.shape[0],2))

TransactionID 0.0
isFraud 0.0
TransactionDT 0.0
TransactionAmt 0.0
ProductCD 0.0
card1 0.0
card2 0.02
card3 0.0
card4 0.0
card5 0.01
card6 0.0
addr1 0.11
addr2 0.11
dist1 0.6
dist2 0.94
P_emaildomain 0.16
R_emaildomain 0.77
C1 0.0
C2 0.0
C3 0.0
C4 0.0
C5 0.0
C6 0.0
C7 0.0
C8 0.0
C9 0.0
C10 0.0
C11 0.0
C12 0.0
C13 0.0
C14 0.0
D1 0.0
D2 0.48
D3 0.45
D4 0.29
D5 0.52
D6 0.88
D7 0.93
D8 0.87
D9 0.87
D10 0.13
D11 0.47
D12 0.89
D13 0.9
D14 0.89
D15 0.15
M1 0.46
M2 0.46
M3 0.46
M4 0.48
M5 0.59
M6 0.29
M7 0.59
M8 0.59
M9 0.59
V1 0.47
V2 0.47
V3 0.47
V4 0.47
V5 0.47
V6 0.47
V7 0.47
V8 0.47
V9 0.47
V10 0.47
V11 0.47
V12 0.13
V13 0.13
V14 0.13
V15 0.13
V16 0.13
V17 0.13
V18 0.13
V19 0.13
V20 0.13
V21 0.13
V22 0.13
V23 0.13
V24 0.13
V25 0.13
V26 0.13
V27 0.13
V28 0.13
V29 0.13
V30 0.13
V31 0.13
V32 0.13
V33 0.13
V34 0.13
V35 0.29
V36 0.29
V37 0.29
V38 0.29
V39 0.29
V40 0.29
V41 0.29
V42 0.29
V43 0.29
V44 0.29
V45 0.29
V46 0.29
V47 0.29
V48 0.29
V49 0.29
V50 0.29
V51 0.29
V52 0.29
V53 0.13
V54 0.13


In [6]:
# creates a list of columns for which 90% of values are missing in train_identity
n= []
for i in train_identity.columns:
    m = np.round(train_identity[i].isnull().sum()/train_identity.shape[0],2)
    if m > 0.90 :
        n.append(i)
n

['id_07',
 'id_08',
 'id_21',
 'id_22',
 'id_23',
 'id_24',
 'id_25',
 'id_26',
 'id_27']

In [7]:
# creates a list of columns for which 90% of values are missing in train_trans
n1= []
for i in train_trans.columns:
    m1 = np.round(train_trans[i].isnull().sum()/train_trans.shape[0],2)
    if m1 > 0.90 :
        n1.append(i)
n1

['dist2', 'D7']

In [8]:
# Drops columns where 90% observations are missing
train_identity = train_identity.drop(n,axis=1)
train_trans = train_trans.drop(n1,axis=1)

In [9]:
train_identity.shape

(144233, 32)

In [10]:
train_trans.shape

(590540, 392)

In [11]:
# Replace missing values by mean for numerical variables and mode for categorical variables in train_identity
for i in train_identity.columns:
    if train_identity[i].dtypes == 'int64' or train_identity[i].dtypes == 'float64':
        train_identity[i] = train_identity[i].fillna(train_identity[i].mean())
    if train_identity[i].dtype == 'object':
        train_identity[i] = train_identity[i].fillna(train_identity[i].mode()[0])

In [12]:
# Replace missing values by mean for numerical variables and mode for categorical variables in train_trans
for i in train_trans.columns:
    if train_trans[i].dtypes == 'int64' or train_trans[i].dtypes == 'float64':
        train_trans[i] = train_trans[i].fillna(train_trans[i].mean())
    if train_trans[i].dtype == 'object':
        train_trans[i] = train_trans[i].fillna(train_trans[i].mode()[0])

In [13]:
# Creating a series of categorical features in train_identity
m =[]
for i in train_identity.columns:
    if train_identity[i].dtype == 'object':
        m.append(i)
m

['id_12',
 'id_15',
 'id_16',
 'id_28',
 'id_29',
 'id_30',
 'id_31',
 'id_33',
 'id_34',
 'id_35',
 'id_36',
 'id_37',
 'id_38',
 'DeviceType',
 'DeviceInfo']

In [14]:
# Creating a series of categorical features in train_trans
m1 =[]
for i in train_trans.columns:
    if train_trans[i].dtype == 'object':
        m1.append(i)
m1

['ProductCD',
 'card4',
 'card6',
 'P_emaildomain',
 'R_emaildomain',
 'M1',
 'M2',
 'M3',
 'M4',
 'M5',
 'M6',
 'M7',
 'M8',
 'M9']

In [15]:
## Making sure that all missing values were imputed
for i in m:
    if train_identity[i].isnull().sum()>0:
        print(i)
for i in m1:
    if train_trans[i].isnull().sum()>0:
        print(i)


In [16]:
train_identity[m].describe()

id_12   id_15   id_16   id_28   id_29       id_30        id_31  \
count     144233  144233  144233  144233  144233      144233       144233   
unique         2       3       2       2       2          75          130   
top     NotFound   Found   Found   Found   Found  Windows 10  chrome 63.0   
freq      123025   70976   81217   79487   78181       87823        25951   

            id_33           id_34   id_35   id_36   id_37   id_38 DeviceType  \
count      144233          144233  144233  144233  144233  144233     144233   
unique        260               4       2       2       2       2          2   
top     1920x1080  match_status:2       T       F       T       F    desktop   
freq        87818          126439   81062  137314  113700   77170      88588   

       DeviceInfo  
count      144233  
unique       1786  
top       Windows  
freq        73289

In [17]:
train_trans[m1].describe()

ProductCD   card4   card6 P_emaildomain R_emaildomain      M1      M2  \
count     590540  590540  590540        590540        590540  590540  590540   
unique         5       4       4            59            60       2       2   
top            W    visa   debit     gmail.com     gmail.com       T       T   
freq      439670  386344  441509        322811        510396  590515  556568   

            M3      M4      M5      M6      M7      M8      M9  
count   590540  590540  590540  590540  590540  590540  590540  
unique       2       3       2       2       2       2       2  
top          T      M0       F       F       F       F       T  
freq    522831  477849  482973  397216  557639  501503  551908

In [18]:
# frequency encoding
def freq_enc(m):
    for i in m:
        mapitem = train_identity[i].value_counts().to_dict()
        train_identity[i]=train_identity[i].map(mapitem)
def freq_enc1(m1):
    for i in m1:
        mapitem = train_trans[i].value_counts().to_dict()
        train_trans[i]=train_trans[i].map(mapitem)


In [19]:
# frequency encoding categorical features with more categories
m_subset=['id_30','id_31','id_33','DeviceInfo']
m1_subset=['P_emaildomain','R_emaildomain']    
freq_enc(m_subset)
freq_enc1(m1_subset)

In [20]:
# Creating a series of categorical features in train_identity (except those frequency encoded)
m =[]
for i in train_identity.columns:
    if train_identity[i].dtype == 'object':
        m.append(i)
# Creating a series of categorical features in train_trans (except those frequency encoded)
m1 =[]
for i in train_trans.columns:
    if train_trans[i].dtype == 'object':
        m1.append(i)

In [21]:
#Creating dummy Variables for identity
train_identity = pd.get_dummies(train_identity,columns=m,drop_first=True)


In [22]:
#Creating dummy Variables for trans
train_trans = pd.get_dummies(train_trans,columns=m1,drop_first=True)


In [23]:
train_identity.shape

(144233, 35)

In [24]:
train_trans.shape

(590540, 400)

In [25]:
#First creating day feature
train_trans['day'] = (train_trans['TransactionDT']//(3600*24)-1)%7

#Then creating hour feature
train_trans['hour'] = (train_trans['TransactionDT']//(3600))%24


In [26]:
#Feature transformation - transform transaction Amount to log scale
train_trans['logTransactionAmt']=np.log(train_trans['TransactionAmt'])


In [27]:
#Merge transactiona nd identity table
train = pd.merge(train_trans,train_identity,on='TransactionID',how = 'inner',sort = False)


In [28]:
train.shape

(144233, 437)

In [29]:
train.head()

TransactionID  isFraud  TransactionDT  TransactionAmt  card1  card2  card3  \
0        2987004        0          86506          50.000   4497  514.0  150.0   
1        2987008        0          86535          15.000   2803  100.0  150.0   
2        2987010        0          86549          75.887  16496  352.0  117.0   
3        2987011        0          86555          16.495   4461  375.0  185.0   
4        2987016        0          86620          30.000   1790  555.0  150.0   

   card5       addr1     addr2  ...  id_28_New  id_29_NotFound  \
0  102.0  420.000000  87.00000  ...          1               1   
1  226.0  337.000000  87.00000  ...          1               1   
2  134.0  290.733794  86.80063  ...          0               0   
3  224.0  290.733794  86.80063  ...          1               1   
4  226.0  170.000000  87.00000  ...          0               0   

   id_34_match_status:0  id_34_match_status:1  id_34_match_status:2  id_35_T  \
0                     0                     0                     1        1   
1                     0                     1                     0        1   
2                     0                     0                     1        0   
3                     0                     0                     1        0   
4                     0                     0                     1        1   

   id_36_T  id_37_T  id_38_T  DeviceType_mobile  
0        0        1        1                  1  
1        0        0        1                  1  
2        0        1        1                  0  
3        0        1        1                  0  
4        0        1        1                  0  

[5 rows x 437 columns]

In [30]:
# Drop unrelated features
train.drop(['TransactionDT','TransactionAmt','TransactionID','day'],axis=1,inplace=True)

In [31]:
X = train.drop('isFraud',axis=1)

In [32]:
y=train['isFraud']

In [33]:
#splitting into train and test set
from sklearn.model_selection import train_test_split

In [34]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=1)

In [35]:
# counting class length in the independent variable
unique,count = np.unique(y_train, return_counts=True)
y_train_dict_value_count={k:v for (k,v) in zip(unique,count)}
y_train_dict_value_count

{0: 89055, 1: 7581}

In [36]:
#import SMOTE
from imblearn import under_sampling, over_sampling
from imblearn.over_sampling import SMOTE

In [37]:
#Perform over-sampling by SMOTE technique by create samples such that both classes are of same length
sm=SMOTE(random_state=1,ratio=1.0)
X_train_res,y_train_res = sm.fit_sample(X_train,y_train)

In [38]:
#Check the length of each class
unique,count = np.unique(y_train_res, return_counts=True)
y_train_smote_value_count={k:v for (k,v) in zip(unique,count)}
y_train_smote_value_count

{0: 89055, 1: 89055}

In [39]:
from sklearn import linear_model
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [40]:
#Fitting linear model
model1 = linear_model.SGDClassifier(loss="log",class_weight='balanced',alpha=0.1,penalty='l2')

In [41]:
model1.fit(X_train_res,y_train_res)

SGDClassifier(alpha=0.1, class_weight='balanced', loss='log')

In [42]:
pred1 = model1.predict(X_test)

In [43]:
classification_report(y_test,pred1)

'              precision    recall  f1-score   support\n\n           0       0.98      0.41      0.58     43860\n           1       0.11      0.88      0.20      3737\n\n    accuracy                           0.45     47597\n   macro avg       0.54      0.65      0.39     47597\nweighted avg       0.91      0.45      0.55     47597\n'

In [44]:
confusion_matrix(y_test,pred1)

array([[18188, 25672],
       [  445,  3292]], dtype=int64)

In [45]:
accuracy_score(y_test,pred1)

0.45128894678236026

In [46]:
from imblearn.pipeline import make_pipeline
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV

In [47]:
# finding mest weight by using GridSearchCV
pipe = make_pipeline(
    SMOTE(),model1
)

weights = np.linspace(0.1, 1, 4)

gsc = GridSearchCV(
    estimator=pipe,
    param_grid={
        'smote__ratio': weights
    },
    scoring='f1',
    cv=3
)
grid_result = gsc.fit(X_train, y_train)

print("Best parameters : %s" % grid_result.best_params_)

Best parameters : {'smote__ratio': 1.0}


In [48]:
#Decision Tree Classifier
from sklearn.tree import DecisionTreeClassifier

In [49]:
dTree = DecisionTreeClassifier(criterion="entropy", max_depth =15)
dTree.fit(X_train_res,y_train_res)
predTree2 = dTree.predict(X_test)
confusion_matrix(y_test,predTree2)

array([[43043,   817],
       [ 1323,  2414]], dtype=int64)

In [50]:
accuracy_score(y_test,predTree2)

0.9550391831417947

In [53]:
from sklearn.metrics import roc_auc_score

In [54]:
roc_auc_score(y_test,predTree2)

0.8136726271991268

In [55]:
from sklearn.ensemble import RandomForestClassifier

In [59]:
# Random Forest Classifier
rfc = RandomForestClassifier()
rfc.fit(X_train_res,y_train_res)
predrfc = rfc.predict(X_test)
confusion_matrix(y_test,predrfc)

array([[43583,   277],
       [ 1337,  2400]], dtype=int64)

In [60]:
accuracy_score(y_test,predrfc)

0.9660902998088114

In [64]:
# Light GBM Classifier
from lightgbm import LGBMClassifier

In [65]:
lgbm = LGBMClassifier(boosting_type='gbdt',
    num_leaves=2**8,
    max_depth=-1,
    learning_rate=0.05,
    n_estimators=1000,
    subsample_for_bin=200000,
    objective='binary',
    class_weight=None,
    min_split_gain=0.0,
    min_child_weight=0.001,
    min_child_samples=20,
    subsample=1.0,
    subsample_freq=1,
    colsample_bytree=0.7,
    reg_alpha=0.0,
    reg_lambda=0.0,
    random_state=None,
    n_jobs=-1,
    silent=True,
    importance_type='split')
lgbm.fit(X_train_res,y_train_res)
predlgbm = lgbm.predict(X_test)
confusion_matrix(y_test,predlgbm)

array([[43765,    95],
       [  843,  2894]], dtype=int64)

In [66]:
accuracy_score(y_test,predlgbm)

0.9802928756014034

In [67]:
roc_auc_score(y_test,predlgbm)

0.8861259998333179